use super::Texts;

pub const TEXTS_EN: Texts = Texts {
    welcome_title: "\x1b[1m Tce \x1b[0m - projects",
    welcome_recents: "Recent projects:",
    welcome_empty: "  (empty - press N to browse folders)",
    welcome_open_new_quit: "Enter - open | N - folder | Ctrl+Q - quit | Ctrl+L - language | Ctrl+K - help",
    welcome_folders: "Folders (from Home/Root):",
    welcome_folder_hint: "Enter open | J/K or Arrows move | P manual path | Esc back",
    welcome_folder_open_current: "[Open current folder]",
    welcome_folder_home: "[Home folder]",
    welcome_folder_root: "[Root /]",
    welcome_folder_up: "[Up ..]",
    welcome_manual_path_hint: "P or / - type path manually",
    welcome_path_prompt: "Path:",
    welcome_status_pos: "pos.",
    welcome_status_enter_esc: " Enter - open  Esc - cancel ",
    hint_sidebar_focus: "sidebar",
    hint_ctrl_b: "Ctrl+B sidebar",
    hint_shift_tab: "Shift+Tab focus",
    hint_ctrl_q_quit: "Ctrl+Q quit",
    hint_ctrl_q_again_quit: "Ctrl+Q again quit",
    hint_ctrl_s_save: "Ctrl+S save",
    hint_ctrl_l_lang: "Ctrl+L language",
    hint_ctrl_k_help: "Ctrl+K help",
    language_menu_title: "Language",
    language_menu_hint: "Up/Down or J/K choose  Enter apply  Esc cancel",
    language_option_en: "English",
    language_option_ru: "Russian",
    help_title: "Hotkeys reference",
    help_hint: "Esc or Ctrl+K - close",
    help_k1: "Ctrl+S - save file",
    help_k2: "Ctrl+Q - quit (twice if unsaved)",
    help_k3: "Ctrl+B - toggle sidebar",
    help_k4: "Shift+Tab / Tab - switch focus",
    help_k5: "Ctrl+L - language section",
    help_k6: "Ctrl+K - hotkeys section",
    help_k7: "Arrows/PageUp/PageDown/Home/End - navigation",
    save_or_quit_double: "Save with Ctrl+S or press Ctrl+Q twice.",
    error_prefix: "Error",
};
