use super::Texts;

pub const TEXTS_EN: Texts = Texts {
    welcome_title: "\x1b[1m Tce \x1b[0m - projects",
    welcome_recents: "Recent projects:",
    welcome_empty: "  (empty - press N to browse folders)",
    welcome_open_new_quit: "Enter - open | N - folder | Ctrl+Q - quit | Ctrl+L - language | Ctrl+H - help",
    welcome_folders: "Folders (from Home/Root):",
    welcome_folder_hint: "Enter open | Arrows move | P manual path | Ctrl+N back",
    welcome_folder_open_current: "[Open current folder]",
    welcome_folder_home: "[Home folder]",
    welcome_folder_root: "[Root /]",
    welcome_folder_up: "[Up ..]",
    welcome_manual_path_hint: "P or / - type path manually",
    welcome_path_prompt: "Path:",
    welcome_status_pos: "pos.",
    welcome_status_enter_esc: " Enter - open  Ctrl+N - back ",
    hint_sidebar_focus: "sidebar",
    hint_ctrl_b: "Ctrl+B sidebar",
    hint_ctrl_r: "Ctrl+R right panel",
    hint_shift_tab: "Shift+Tab focus",
    hint_ctrl_q_quit: "Ctrl+Q quit",
    hint_ctrl_q_again_quit: "Ctrl+Q again quit",
    hint_ctrl_s_save: "Ctrl+S save",
    hint_ctrl_l_lang: "Ctrl+L language",
    hint_ctrl_k_help: "Ctrl+H help",
    hint_sidebar_focus_actions: "sidebar: Enter open | M menu | Ctrl+N new file | Del delete | Ctrl+R right panel | G/H/E/U/L/C/I LLM/agent",
    hint_tabs_focus_actions: "tabs: Left/Right | Enter | Del/Ctrl+W | Ctrl+J/N reorder | Ctrl+X pin | editor Ctrl+arrows reorder",
    language_menu_title: "Language",
    language_menu_hint: "Up/Down choose  Enter apply  Ctrl+L close",
    language_option_en: "English",
    language_option_ru: "Russian",
    help_title: "Hotkeys reference",
    help_hint: "Ctrl+H - close",
    help_k1: "Ctrl+S - save file",
    help_k2: "Ctrl+Q - quit (twice if unsaved)",
    help_k3: "Ctrl+B - toggle sidebar",
    help_k4: "Shift+Tab / Tab - switch focus",
    help_k5: "Ctrl+L - language section",
    help_k6: "UI: Ctrl+H help, Ctrl+L language, Ctrl+B left sidebar, Ctrl+R right panel, Tab/Shift+Tab focus.",
    help_k7: "Navigation: arrows/Home/End/PageUp/PageDown; Ctrl+A back; Ctrl+Z forward; Ctrl+T symbols; Ctrl+Y go to line.",
    help_k8: "Files/tabs: Ctrl+O quick open; Ctrl+P/U next/prev tab; Ctrl+W close tab; Ctrl+X pin tab; Ctrl+J palette.",
    find_in_file_prompt: "Find in file:",
    find_in_file_hint: "Enter jump | Tab/arrows match | Esc close",
    help_k9: "Search/edit: Ctrl+\\ find in file; Ctrl+F project search; Ctrl+G replace current / LLM ask; Ctrl+C/V undo/redo; Ctrl+D/E multi/sync edit.",
    help_k10: "LLM/Agent: Enter sends in right chat panel; Ctrl+C cancels LLM; sidebar: G ask, H history, E agent events, U unsafe tools, L run loop, C clear history, I insert answer; plus Git commands in palette.",
    save_or_quit_double: "Save with Ctrl+S or press Ctrl+Q twice.",
    error_prefix: "Error",
    tip_no_in_file_matches: "No matches in this file",
    llm_ask_prefix: "LLM ask:",
    llm_prompt_empty: "Enter a prompt for LLM",
    llm_history_cleared: "LLM history cleared",
    llm_disabled: "LLM is disabled in settings (llm_enabled=false)",
    llm_service_ok: "LLM service is available",
    llm_service_not_ok: "LLM service returned ok=false",
    llm_current_line_empty: "Current line is empty",
    llm_busy: "LLM is already handling another request",
    llm_running: "LLM: request in progress... (Ctrl+C to cancel)",
    llm_stream_failed: "LLM stream ended with an error",
    llm_cancelled: "LLM request cancelled",
    no_assistant_answer: "No assistant answer available to insert",
    llm_history_overlay_title: "LLM History  (messages {}-{} of {})",
    agent_events_overlay_title: "Agent Events  (lines {}-{} of {})",
    agent_running: "Agent: running step loop...",
    agent_steps_summary_fmt: "Agent: steps={}, finish={}, summary={}",
    agent_error_prefix: "Agent error: ",
    agent_stream_failed: "Agent worker ended with an error",
    agent_unsafe_enabled: "Agent unsafe tools: ENABLED",
    agent_unsafe_disabled: "Agent unsafe tools: DISABLED",
    agent_unsafe_confirm_tip: "Confirm unsafe tools: Y enable, N/Esc cancel",
    agent_unsafe_cancelled: "Unsafe tools enabling cancelled",
    agent_unsafe_confirm_overlay: "Enable unsafe agent tools? Y - enable, N/Esc - cancel",
    tip_no_word_under_cursor: "No word under cursor",
    tip_autosaved: "Autosaved",
    tip_move_picked: "Move picked. Navigate and press P to drop",
    tip_move_cancelled: "Move cancelled",
    tip_invalid_source: "Invalid source",
    tip_source_target_same: "Source and target are the same",
    tip_target_exists: "Target already exists",
    tip_moved: "Moved",
    tip_name_empty: "Name is empty",
    tip_no_selected_target: "No selected target",
    tip_tab_is_pinned: "Tab is pinned. Press Ctrl+X to unpin",
    tip_tab_pinned: "Tab pinned",
    tip_tab_unpinned: "Tab unpinned",
    tip_no_back_history: "No back history",
    tip_no_forward_history: "No forward history",
    tip_folder_not_found: "Folder not found",
    tip_delete_confirm: "Press Delete again to confirm",
    tip_replace_text_first: "Type replacement text first",
    tip_no_search_matches_replace: "No search matches to replace",
    tip_replaced_current_match: "Replaced current match",
    tip_current_not_replaced: "Current match was not replaced",
    tip_replace_first_then_ctrl_r: "Type replacement first, then Ctrl+R again",
    tip_press_enter_confirm_replace_all: "Press Enter to confirm replace all",
    tip_no_occurrences_replaced: "No occurrences replaced",
    tip_multi_edit_replaced_fmt: "Multi-edit replaced {} occurrences",
    tip_cannot_start_sync_edit: "Cannot start sync edit for this word",
    tip_no_occurrences_found: "No occurrences found",
    tip_autosave_enabled: "Autosave enabled",
    tip_autosave_disabled: "Autosave disabled",
    tip_no_diagnostics_yet: "No diagnostics yet",
    tip_font_zoom_fmt: "Font zoom: {}",
    tip_line_spacing_comfortable: "Line spacing: comfortable",
    tip_line_spacing_compact: "Line spacing: compact",
    tip_ligatures_on: "Ligatures: on",
    tip_ligatures_off: "Ligatures: off",
    tip_lsp_wave_fmt: "LSP v1: {} | current: {}",
    yes: "yes",
    no: "no",
    git_title_status: "Git: status",
    git_title_diff_unstaged: "Git: diff (unstaged)",
    git_title_diff_staged: "Git: diff (staged)",
    git_title_log: "Git: log",
    tip_agent_busy: "Another LLM/Agent request is already running",
    tip_assistant_answer_inserted: "Assistant answer inserted into document",
    tip_open_file_first: "Open a file first",
    tip_failed_run_rustc: "Failed to run rustc",
    tip_rust_check_no_diagnostics: "Rust check: no diagnostics",
    tip_rust_diagnostics_ready: "Rust diagnostics ready",
    tip_no_diagnostics_for_filter: "No diagnostics for this filter",
    tip_empty_output: "(empty output)",
};
