use super::Texts;

pub const TEXTS_EN: Texts = Texts {
    welcome_title: "\x1b[1m Tce \x1b[0m - projects",
    welcome_recents: "Recent projects:",
    welcome_empty: "  (empty - press N to browse folders)",
    welcome_open_new_quit: "Enter - open | N - folder | Ctrl+Q - quit | Ctrl+L - language | Ctrl+K - help",
    welcome_folders: "Folders (from Home/Root):",
    welcome_folder_hint: "Enter open | Arrows move | P manual path | Ctrl+N back",
    welcome_folder_open_current: "[Open current folder]",
    welcome_folder_home: "[Home folder]",
    welcome_folder_root: "[Root /]",
    welcome_folder_up: "[Up ..]",
    welcome_manual_path_hint: "P or / - type path manually",
    welcome_path_prompt: "Path:",
    welcome_status_pos: "pos.",
    welcome_status_enter_esc: " Enter - open  Ctrl+N - back ",
    hint_sidebar_focus: "sidebar",
    hint_ctrl_b: "Ctrl+B sidebar",
    hint_shift_tab: "Shift+Tab focus",
    hint_ctrl_q_quit: "Ctrl+Q quit",
    hint_ctrl_q_again_quit: "Ctrl+Q again quit",
    hint_ctrl_s_save: "Ctrl+S save",
    hint_ctrl_l_lang: "Ctrl+L language",
    hint_ctrl_k_help: "Ctrl+K help",
    hint_sidebar_focus_actions: "sidebar: Enter open | M menu | Ctrl+N new file | Del delete",
    hint_tabs_focus_actions: "tabs: Left/Right | Enter | Del/Ctrl+W | Ctrl+J/N reorder | Ctrl+X pin | editor Ctrl+arrows reorder",
    language_menu_title: "Language",
    language_menu_hint: "Up/Down choose  Enter apply  Ctrl+L close",
    language_option_en: "English",
    language_option_ru: "Russian",
    help_title: "Hotkeys reference",
    help_hint: "Ctrl+K - close",
    help_k1: "Ctrl+S - save file",
    help_k2: "Ctrl+Q - quit (twice if unsaved)",
    help_k3: "Ctrl+B - toggle sidebar",
    help_k4: "Shift+Tab / Tab - switch focus",
    help_k5: "Ctrl+L - language section",
    help_k6: "Ctrl+K - hotkeys section",
    help_k7: "Arrows/PageUp/PageDown/Home/End - navigation",
    help_k8: "Tabs: Ctrl+P/U switch, Ctrl+W close, Ctrl+X pin; tab bar Ctrl+J/N reorder; editor Ctrl+Left/Right reorder | Ctrl+J palette | Nav Ctrl+A/Z | Edit Ctrl+C/V undo/redo | Ctrl+D/E multi/sync | Ctrl+T/Y symbols/line | Ctrl+O open | Ctrl+F/G/R project search/replace",
    find_in_file_prompt: "Find in file:",
    find_in_file_hint: "Enter jump | Tab/arrows match | Esc close",
    help_k9: "Ctrl+\\ - find in current file (case-insensitive). Ctrl+F - search across project.",
    help_k10: "Git: command palette - Git: Status / Diff / Log (read-only). Enter on status line opens file.",
    save_or_quit_double: "Save with Ctrl+S or press Ctrl+Q twice.",
    error_prefix: "Error",
    tip_no_in_file_matches: "No matches in this file",
};
