mod en;
mod ru;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Language {
    Ru,
    En,
}

pub struct Texts {
    pub welcome_title: &'static str,
    pub welcome_recents: &'static str,
    pub welcome_empty: &'static str,
    pub welcome_open_new_quit: &'static str,
    pub welcome_folders: &'static str,
    pub welcome_folder_hint: &'static str,
    pub welcome_folder_open_current: &'static str,
    pub welcome_folder_home: &'static str,
    pub welcome_folder_root: &'static str,
    pub welcome_folder_up: &'static str,
    pub welcome_manual_path_hint: &'static str,
    pub welcome_path_prompt: &'static str,
    pub welcome_status_pos: &'static str,
    pub welcome_status_enter_esc: &'static str,
    pub hint_sidebar_focus: &'static str,
    pub hint_ctrl_b: &'static str,
    pub hint_ctrl_r: &'static str,
    pub hint_shift_tab: &'static str,
    pub hint_ctrl_q_quit: &'static str,
    pub hint_ctrl_q_again_quit: &'static str,
    pub hint_ctrl_s_save: &'static str,
    pub hint_ctrl_l_lang: &'static str,
    pub hint_ctrl_k_help: &'static str,
    pub hint_sidebar_focus_actions: &'static str,
    pub hint_tabs_focus_actions: &'static str,
    pub language_menu_title: &'static str,
    pub language_menu_hint: &'static str,
    pub language_option_en: &'static str,
    pub language_option_ru: &'static str,
    pub help_title: &'static str,
    pub help_hint: &'static str,
    pub help_k1: &'static str,
    pub help_k2: &'static str,
    pub help_k3: &'static str,
    pub help_k4: &'static str,
    pub help_k5: &'static str,
    pub help_k6: &'static str,
    pub help_k7: &'static str,
    pub help_k8: &'static str,
    pub find_in_file_prompt: &'static str,
    pub find_in_file_hint: &'static str,
    pub help_k9: &'static str,
    pub help_k10: &'static str,
    pub save_or_quit_double: &'static str,
    pub error_prefix: &'static str,
    pub tip_no_in_file_matches: &'static str,
    pub llm_ask_prefix: &'static str,
    pub llm_prompt_empty: &'static str,
    pub llm_history_cleared: &'static str,
    pub llm_disabled: &'static str,
    pub llm_service_ok: &'static str,
    pub llm_service_not_ok: &'static str,
    pub llm_current_line_empty: &'static str,
    pub llm_busy: &'static str,
    pub llm_running: &'static str,
    pub llm_stream_failed: &'static str,
    pub llm_cancelled: &'static str,
    pub no_assistant_answer: &'static str,
    pub llm_history_overlay_title: &'static str,
    pub agent_events_overlay_title: &'static str,
    pub agent_running: &'static str,
    pub agent_steps_summary_fmt: &'static str,
    pub agent_error_prefix: &'static str,
    pub agent_stream_failed: &'static str,
    pub agent_unsafe_enabled: &'static str,
    pub agent_unsafe_disabled: &'static str,
    pub agent_unsafe_confirm_tip: &'static str,
    pub agent_unsafe_cancelled: &'static str,
    pub agent_unsafe_confirm_overlay: &'static str,
    pub tip_no_word_under_cursor: &'static str,
    pub tip_autosaved: &'static str,
    pub tip_move_picked: &'static str,
    pub tip_move_cancelled: &'static str,
    pub tip_invalid_source: &'static str,
    pub tip_source_target_same: &'static str,
    pub tip_target_exists: &'static str,
    pub tip_moved: &'static str,
    pub tip_name_empty: &'static str,
    pub tip_no_selected_target: &'static str,
    pub tip_tab_is_pinned: &'static str,
    pub tip_tab_pinned: &'static str,
    pub tip_tab_unpinned: &'static str,
    pub tip_no_back_history: &'static str,
    pub tip_no_forward_history: &'static str,
    pub tip_folder_not_found: &'static str,
    pub tip_delete_confirm: &'static str,
    pub tip_replace_text_first: &'static str,
    pub tip_no_search_matches_replace: &'static str,
    pub tip_replaced_current_match: &'static str,
    pub tip_current_not_replaced: &'static str,
    pub tip_replace_first_then_ctrl_r: &'static str,
    pub tip_press_enter_confirm_replace_all: &'static str,
    pub tip_no_occurrences_replaced: &'static str,
    pub tip_multi_edit_replaced_fmt: &'static str,
    pub tip_cannot_start_sync_edit: &'static str,
    pub tip_no_occurrences_found: &'static str,
    pub tip_autosave_enabled: &'static str,
    pub tip_autosave_disabled: &'static str,
    pub tip_no_diagnostics_yet: &'static str,
    pub tip_font_zoom_fmt: &'static str,
    pub tip_line_spacing_comfortable: &'static str,
    pub tip_line_spacing_compact: &'static str,
    pub tip_ligatures_on: &'static str,
    pub tip_ligatures_off: &'static str,
    pub tip_lsp_wave_fmt: &'static str,
    pub yes: &'static str,
    pub no: &'static str,
    pub git_title_status: &'static str,
    pub git_title_diff_unstaged: &'static str,
    pub git_title_diff_staged: &'static str,
    pub git_title_log: &'static str,
    pub tip_agent_busy: &'static str,
    pub tip_assistant_answer_inserted: &'static str,
    pub tip_open_file_first: &'static str,
    pub tip_failed_run_rustc: &'static str,
    pub tip_rust_check_no_diagnostics: &'static str,
    pub tip_rust_diagnostics_ready: &'static str,
    pub tip_no_diagnostics_for_filter: &'static str,
    pub tip_empty_output: &'static str,
}

pub fn texts(lang: Language) -> &'static Texts {
    match lang {
        Language::Ru => &ru::TEXTS_RU,
        Language::En => &en::TEXTS_EN,
    }
}
