use super::Texts;

pub const TEXTS_RU: Texts = Texts {
    welcome_title: "\x1b[1m Tce \x1b[0m - проекты",
    welcome_recents: "Недавние проекты:",
    welcome_empty: "  (пусто - нажми N для выбора папки)",
    welcome_open_new_quit: "Enter - открыть | N - папка | Ctrl+Q - выход | Ctrl+L - язык | Ctrl+K - справка",
    welcome_folders: "Папки (от Home/Root):",
    welcome_folder_hint: "Enter открыть | Стрелки | P ручной путь | Ctrl+N назад",
    welcome_folder_open_current: "[Открыть текущую папку]",
    welcome_folder_home: "[Домашняя папка]",
    welcome_folder_root: "[Корень /]",
    welcome_folder_up: "[Вверх ..]",
    welcome_manual_path_hint: "P или / - ввести путь вручную",
    welcome_path_prompt: "Путь:",
    welcome_status_pos: "поз.",
    welcome_status_enter_esc: " Enter - открыть  Ctrl+N - назад ",
    hint_sidebar_focus: "сайдбар",
    hint_ctrl_b: "Ctrl+B сайдбар",
    hint_shift_tab: "Shift+Tab фокус",
    hint_ctrl_q_quit: "Ctrl+Q выход",
    hint_ctrl_q_again_quit: "Ctrl+Q снова выйти",
    hint_ctrl_s_save: "Ctrl+S сохранить",
    hint_ctrl_l_lang: "Ctrl+L язык",
    hint_ctrl_k_help: "Ctrl+K справка",
    hint_sidebar_focus_actions: "сайдбар: Enter открыть | M меню | Ctrl+N файл | Del удалить",
    hint_tabs_focus_actions: "табы: Left/Right выбор | Enter открыть | Del/Ctrl+W закрыть | Ctrl+J/Ctrl+N порядок | Ctrl+X pin",
    language_menu_title: "Язык",
    language_menu_hint: "Вверх/Вниз выбор  Enter применить  Ctrl+L закрыть",
    language_option_en: "Английский",
    language_option_ru: "Русский",
    help_title: "Справочник горячих клавиш",
    help_hint: "Ctrl+K - закрыть",
    help_k1: "Ctrl+S - сохранить файл",
    help_k2: "Ctrl+Q - выход (дважды если есть несохраненное)",
    help_k3: "Ctrl+B - показать/скрыть сайдбар",
    help_k4: "Shift+Tab / Tab - переключить фокус",
    help_k5: "Ctrl+L - раздел выбора языка",
    help_k6: "Ctrl+K - раздел горячих клавиш",
    help_k7: "Стрелки/PageUp/PageDown/Home/End - навигация",
    help_k8: "Табы: Ctrl+P след., Ctrl+U пред., Ctrl+W закрыть, Ctrl+X pin, Ctrl+J влево, Ctrl+N вправо | Ctrl+J (вне табов) command palette | Навигация: Ctrl+A назад, Ctrl+Z вперед | Редакт: Ctrl+C undo, Ctrl+V redo | Ctrl+D мульти-редакт, Ctrl+E синхронный ввод | Ctrl+T символы | Ctrl+Y строка | Ctrl+O файл | Ctrl+F поиск, Ctrl+G заменить текущий, Ctrl+R replace-all",
    save_or_quit_double: "Сначала Ctrl+S (сохранить) или Ctrl+Q дважды.",
    error_prefix: "Ошибка",
};
