use super::Texts;

pub const TEXTS_RU: Texts = Texts {
    welcome_title: "\x1b[1m Tce \x1b[0m - проекты",
    welcome_recents: "Недавние проекты:",
    welcome_empty: "  (пусто - нажми N для выбора папки)",
    welcome_open_new_quit: "Enter - открыть | N - папка | Ctrl+Q - выход | Ctrl+L - язык | Ctrl+K - справка",
    welcome_folders: "Папки (от Home/Root):",
    welcome_folder_hint: "Enter открыть | Стрелки | P ручной путь | Ctrl+N назад",
    welcome_folder_open_current: "[Открыть текущую папку]",
    welcome_folder_home: "[Домашняя папка]",
    welcome_folder_root: "[Корень /]",
    welcome_folder_up: "[Вверх ..]",
    welcome_manual_path_hint: "P или / - ввести путь вручную",
    welcome_path_prompt: "Путь:",
    welcome_status_pos: "поз.",
    welcome_status_enter_esc: " Enter - открыть  Ctrl+N - назад ",
    hint_sidebar_focus: "сайдбар",
    hint_ctrl_b: "Ctrl+B сайдбар",
    hint_shift_tab: "Shift+Tab фокус",
    hint_ctrl_q_quit: "Ctrl+Q выход",
    hint_ctrl_q_again_quit: "Ctrl+Q снова выйти",
    hint_ctrl_s_save: "Ctrl+S сохранить",
    hint_ctrl_l_lang: "Ctrl+L язык",
    hint_ctrl_k_help: "Ctrl+K справка",
    hint_sidebar_focus_actions: "сайдбар: Enter открыть | M меню | Ctrl+N файл | Del удалить",
    hint_tabs_focus_actions: "табы: Left/Right | Enter | Del/Ctrl+W | Ctrl+J/N порядок | Ctrl+X pin | в редакторе Ctrl+стрелки - порядок",
    language_menu_title: "Язык",
    language_menu_hint: "Вверх/Вниз выбор  Enter применить  Ctrl+L закрыть",
    language_option_en: "Английский",
    language_option_ru: "Русский",
    help_title: "Справочник горячих клавиш",
    help_hint: "Ctrl+K - закрыть",
    help_k1: "Ctrl+S - сохранить файл",
    help_k2: "Ctrl+Q - выход (дважды если есть несохраненное)",
    help_k3: "Ctrl+B - показать/скрыть сайдбар",
    help_k4: "Shift+Tab / Tab - переключить фокус",
    help_k5: "Ctrl+L - раздел выбора языка",
    help_k6: "Ctrl+K - раздел горячих клавиш",
    help_k7: "Стрелки/PageUp/PageDown/Home/End - навигация",
    help_k8: "Табы: Ctrl+P/U перекл., Ctrl+W закрыть, Ctrl+X pin; в строке табов Ctrl+J/N порядок; в редакторе Ctrl+Left/Right порядок | Ctrl+J палитра | Ctrl+A/Z назад/вперёд | Ctrl+C/V undo/redo | Ctrl+D/E мульти/синхр. | Ctrl+T/Y символы/строка | Ctrl+O файл | Ctrl+F/G/R поиск по проекту",
    find_in_file_prompt: "Поиск в файле:",
    find_in_file_hint: "Enter - перейти | Tab/стрелки - совпадение | Esc - выход",
    help_k9: "Ctrl+\\ - поиск в текущем файле (без учёта регистра). Ctrl+F - поиск по проекту.",
    help_k10: "Git: палитра команд - Git: Status / Diff / Log (только просмотр). Enter на строке статуса - открыть файл.",
    save_or_quit_double: "Сначала Ctrl+S (сохранить) или Ctrl+Q дважды.",
    error_prefix: "Ошибка",
    tip_no_in_file_matches: "В этом файле совпадений нет",
};
